Condidature/Controllers/CondidatController.cs
using Condidature.Models;
using Condidature.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Microsoft.AspNetCore.Hosting;

namespace Condidature.Controllers
{
    public class CondidatController : Controller
    {
        private readonly ICondidate _ICondidate;
        private readonly IWebHostEnvironment _environement;
        public CondidatController(ICondidate ICondidate, IWebHostEnvironment environement)
        {
            _ICondidate = ICondidate;
            _environement = environement;

        }
        public IActionResult Index()
        {
            return View();
        }

        //Registration process
        [HttpGet]
        public ViewResult Register()
        {
            return View();
        }

       

        [HttpPost]
        public IActionResult Register(Condidat condidat, IFormFile CV)
        {
            if (CV != null && CV.Length > 0)
            {
                // Récupérer le nom et le prénom du candidat depuis le modèle
                string nom = condidat.Nom;
                string prenom = condidat.Prenom;

                // Générer le chemin du répertoire basé sur le nom et le prénom du candidat
                string directoryPath = Path.Combine(_environement.WebRootPath + "/CV/", nom + "_" + prenom);

                // Créer le répertoire s'il n'existe pas déjà
                if (!Directory.Exists(directoryPath))
                {
                    Directory.CreateDirectory(directoryPath);
                }

                // Générer le nom de fichier unique pour le CV (pour éviter les conflits)
                string fileName = nom + "_" + prenom + Path.GetExtension(CV.FileName); 

                // Générer le chemin complet du fichier
                string filePath = Path.Combine(directoryPath, fileName);

                // Enregistrer le fichier CV sur le disque
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    CV.CopyTo(stream);
                }

                // Ajouter le chemin du fichier CV dans le modèle de candidature
                condidat.CV = filePath;

                // Enregistrer le modèle de candidature dans la base de données ou effectuer d'autres opérations nécessaires
                _ICondidate.Register(condidat);


                // Afficher un message de confirmation

                TempData["ConfirmationMessage"] = "Inscription réussie. Vous pouvez maintenant vous connecter.";

                // Rediriger vers une page de confirmation 
                return RedirectToAction("Index");

            }

            // Si aucun fichier CV n'est fourni Afficher à nouveau le formulaire 
            return View("Register", condidat); 
        }

    

    

        }

    }

Condidature/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Condidature</title>
    <link href="~/css/style.css" rel="stylesheet" asp-append-version="true" />
    <link rel="stylesheet" href="~/Condidature.styles.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    

</head>
<body>

    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">WeCount</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                       
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Condidat" asp-action="Register">Nouvelle condidature</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Login">Se connecter</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

    </header>
  
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Condidature - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>